site_name: ignf_gpf_api

theme:
  name: "readthedocs"
  locale: fr

nav:
  - index.md
  - configuration.md
  - comme-executable.md
  - comme-module.md
  - upload_descriptor.md
  - workflow.md
  - development.md
